import datetime

def generate_markdown_report(item, stability_score, evaluation_metrics, clinician_notes=""):
    """
    Generates a structured Markdown report for a specific diagnostic case.
    """
    report = f"""# AI Diagnostic Evidence Report
**Date:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Patient/Image ID:** {item['filename']}

---

## 1. Diagnostic Summary
| Field | Value |
|-------|-------|
| **True Label** | {item['true_label']} |
| **AI Prediction** | {item['predicted_label']} |
| **Confidence** | {item['confidence']:.2%} |
| **Stability Score** | {stability_score:.2f}/1.0 |

> **Stability Note:** This score measures how robust the prediction is to small input perturbations. A score > 0.8 identifies high clinical reliability.

---

## 2. Explainability Evidence
The following visual transformations were used to validate the diagnosis:

- **Grad-CAM (Attention):** Shows the specific lung regions the AI focused on for this classification.
- **Counterfactual (What-If):** A generative visualization of the '{ "NORMAL" if item['predicted_label'] == "PNEUMONIA" else "PNEUMONIA" }' version of this scan.
- **Difference Map:** Highlights the exact pixels modified by the GAN to achieve the counterfactual state (e.g., cleared opacities).

---

## 3. Quantitative Validation
| Metric | Value | Reference |
|--------|-------|-----------|
| **SSIM** | {item.get('ssim', 'N/A')} | Structural Similarity (Higher is better) |
| **LPIPS** | {item.get('lpips', 'N/A')} | Perceptual Distance (Lower is better) |

---

## 4. Clinician Notes
{clinician_notes if clinician_notes else "*No notes provide.*"}

---
**Disclaimer:** This report was generated by an automated AI diagnostic system for research purposes. All findings should be verified by a board-certified radiologist.
"""
    return report
